import type { Book } from "./types"

export const genres = [
  "Fantasy",
  "Science Fiction",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Non-Fiction",
  "Biography",
  "Self-Help",
  "Horror",
  "Young Adult",
  "Children's",
]

export const moods = [
  "Uplifting",
  "Dark",
  "Funny",
  "Emotional",
  "Thought-provoking",
  "Relaxing",
  "Adventurous",
  "Romantic",
  "Suspenseful",
  "Inspiring",
]

export const books: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "Between life and death there is a library, and within that library, the shelves go on forever.",
    longDescription:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    coverImage: "/images/book1.png",
    rating: 4.2,
    reviewCount: 1243,
    genres: ["Fiction", "Fantasy", "Self-Help"],
    moods: ["Uplifting", "Thought-provoking", "Emotional"],
    publishDate: "August 13, 2020",
    pages: 304,
    language: "English",
    isbn: "9780525559474",
    publisher: "Viking",
  },
  {
    id: "2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description: "A lone astronaut must save the earth from disaster in this incredible new science-based thriller.",
    longDescription:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it. All he knows is that he's been asleep for a very, very long time. And he's just been awakened to find himself millions of miles from home, with nothing but two corpses for company.",
    coverImage: "/images/book2.png",
    rating: 4.7,
    reviewCount: 987,
    genres: ["Science Fiction", "Adventure", "Mystery"],
    moods: ["Adventurous", "Suspenseful", "Thought-provoking"],
    publishDate: "May 4, 2021",
    pages: 496,
    language: "English",
    isbn: "9780593135204",
    publisher: "Ballantine Books",
  },
  {
    id: "3",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    description: "A life no one will remember. A story you will never forget.",
    longDescription:
      "France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets. Thus begins the extraordinary life of Addie LaRue, and a dazzling adventure that will play out across centuries and continents, across history and art, as a young woman learns how far she will go to leave her mark on the world.",
    coverImage: "/images/book3.png",
    rating: 4.3,
    reviewCount: 1567,
    genres: ["Fantasy", "Historical Fiction", "Romance"],
    moods: ["Emotional", "Thought-provoking", "Romantic"],
    isFavorite: true,
    publishDate: "October 6, 2020",
    pages: 448,
    language: "English",
    isbn: "9780765387561",
    publisher: "Tor Books",
  },
  {
    id: "4",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    description:
      "From the Nobel Prize-winning author, a novel about an Artificial Friend who observes the world around her.",
    longDescription:
      "From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse, and of those who pass on the street outside. She remains hopeful that a customer will soon choose her, but when the possibility emerges that her circumstances may change forever, Klara is warned not to invest too much in the promises of humans.",
    coverImage: "/images/book4.png",
    rating: 3.9,
    reviewCount: 876,
    genres: ["Science Fiction", "Literary Fiction"],
    moods: ["Thought-provoking", "Emotional", "Dark"],
    publishDate: "March 2, 2021",
    pages: 320,
    language: "English",
    isbn: "9780571364879",
    publisher: "Faber & Faber",
  },
  {
    id: "5",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    description: "A tale of gods, kings, immortal fame, and the human heart.",
    longDescription:
      "Greece in the age of heroes. Patroclus, an awkward young prince, has been exiled to the court of King Peleus and his perfect son Achilles. By all rights their paths should never cross, but Achilles takes the shamed prince as his friend, and as they grow into young men skilled in the arts of war and medicine their bond blossoms into something deeper - despite the displeasure of Achilles' mother Thetis, a cruel sea goddess.",
    coverImage: "/images/book5.png",
    rating: 4.5,
    reviewCount: 2134,
    genres: ["Historical Fiction", "Fantasy", "Romance"],
    moods: ["Emotional", "Romantic", "Dark"],
    isFavorite: true,
    publishDate: "September 20, 2011",
    pages: 416,
    language: "English",
    isbn: "9780062060617",
    publisher: "Ecco",
  },
  {
    id: "6",
    title: "Educated",
    author: "Tara Westover",
    description:
      "A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    longDescription:
      "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent. When another brother got himself into college, Tara decided to try a new kind of life.",
    coverImage: "/images/book6.png",
    rating: 4.4,
    reviewCount: 1876,
    genres: ["Non-Fiction", "Biography", "Memoir"],
    moods: ["Inspiring", "Emotional", "Thought-provoking"],
    publishDate: "February 20, 2018",
    pages: 352,
    language: "English",
    isbn: "9780399590504",
    publisher: "Random House",
  },
  {
    id: "7",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    description: "A magical island. A dangerous task. A burning secret.",
    longDescription:
      "Linus Baker leads a quiet, solitary life. At forty, he lives in a tiny house with a devious cat and his old records. As a Case Worker at the Department in Charge Of Magical Youth, he spends his days overseeing the well-being of children in government-sanctioned orphanages. When Linus is unexpectedly summoned by Extremely Upper Management he's given a curious and highly classified assignment: travel to Marsyas Island Orphanage, where six dangerous children reside.",
    coverImage: "/images/book7.png",
    rating: 4.6,
    reviewCount: 1432,
    genres: ["Fantasy", "Fiction", "LGBT"],
    moods: ["Uplifting", "Funny", "Heartwarming"],
    isFavorite: true,
    publishDate: "March 17, 2020",
    pages: 396,
    language: "English",
    isbn: "9781250217288",
    publisher: "Tor Books",
  },
  {
    id: "8",
    title: "Circe",
    author: "Madeline Miller",
    description:
      "The daring, dazzling and highly anticipated follow-up to the New York Times bestseller The Song of Achilles.",
    longDescription:
      "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother. Turning to the world of mortals for companionship, she discovers that she does possess power—the power of witchcraft, which can transform rivals into monsters and menace the gods themselves.",
    coverImage: "/images/book8.png",
    rating: 4.3,
    reviewCount: 1987,
    genres: ["Fantasy", "Historical Fiction", "Mythology"],
    moods: ["Adventurous", "Emotional", "Empowering"],
    publishDate: "April 10, 2018",
    pages: 400,
    language: "English",
    isbn: "9780316556347",
    publisher: "Little, Brown and Company",
  },
  {
    id: "9",
    title: "Atomic Habits",
    author: "James Clear",
    description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones.",
    longDescription:
      "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    coverImage: "/images/book9.png",
    rating: 4.8,
    reviewCount: 2543,
    genres: ["Self-Help", "Non-Fiction", "Psychology"],
    moods: ["Inspiring", "Thought-provoking", "Practical"],
    publishDate: "October 16, 2018",
    pages: 320,
    language: "English",
    isbn: "9780735211292",
    publisher: "Avery",
  },
  {
    id: "10",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "A shocking psychological thriller of a woman's act of violence against her husband—and of the therapist obsessed with uncovering her motive.",
    longDescription:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    coverImage: "/images/book10.png",
    rating: 4.1,
    reviewCount: 1765,
    genres: ["Thriller", "Mystery", "Psychological Fiction"],
    moods: ["Suspenseful", "Dark", "Thought-provoking"],
    publishDate: "February 5, 2019",
    pages: 336,
    language: "English",
    isbn: "9781250301697",
    publisher: "Celadon Books",
  },
]
